### ISSUE TITLE
Training with custom data

### ISSUE THREAD

**Issue by dongyun-kim-arch** [williamyang1991/DualStyleGAN#48]
Hello!

I would like to train DualStyleGAN with my own data which is a particular style of human face datasets such as Pixar or Arcane.
I collected around 300 images and did all the preprocessing such as alignment and super-resolution.

Considering my domain (face) is similar to what you experimented with in your paper, I am not sure I could directly utilize your pertained model. For example, could I skip facial destylization and start with stage 3 in progressive fine-tuning? or should I start with step 3 in facial destylization?

It would be great if you could explain custom dataset training sequentially. 
Thank you!

**Comment by williamyang1991** [comment]
You still need to run Facial Destylization, since we need to prepare paired training data to train DualStyleGAN (i.e., need to obtain the intrinsic and extrinsic style codes).

Then, in Progressive Fine-Tuning, you can skip step 1 & 2 by loading my pretrained model, and only run step 3.

**Comment by dongyun-kim-arch** [comment]
Thanks for answering it!
So does it mean I can skip step2 in facial destylization but need to do step 3? Or should I do both?

**Comment by williamyang1991** [comment]
You can try with or without step 2.
I don't know which one is better.

**Comment by dongyun-kim-arch** [comment]
Thanks!
 I tried to train step2 in Facial Destylization, but faced an error. 

I prepared 300 images with alignment and super resolution script, 1024x1024, and saved them in /data/mystyle/images/train
and then run this command 
python ./model/stylegan/prepare_data.py --out ./data/mystyle/lmdb/ --n_worker 4 --size 1024 ./data/mystyle/images/
It created two files in lmdb folder which are data.mdb and  lock.mdb.

and run this command, 
python -m torch.distributed.launch --nproc_per_node=1 --master_port=8765 finetune_stylegan.py --iter 600 --batch 4 --ckpt ./checkpoint/stylegan2-ffhq-config-f.pt --style mystyle --augment ./data/mystyle/lmdb/
but faced this error. Could you point out what I am wrong here?


load model: ./checkpoint/stylegan2-ffhq-config-f.pt
  0%|                                                                                                               | 0/600 [00:00<?, ?it/s]/home/donghyun/Desktop/training/DualStyleGAN/model/stylegan/op/conv2d_gradfix.py:88: UserWarning: conv2d_gradfix not supported on PyTorch 1.12.1+cu113. Falling back to torch.nn.functional.conv2d().
  warnings.warn(
  0%|                                                                                                               | 0/600 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "finetune_stylegan.py", line 391, in <module>
    train(args, loader, generator, discriminator, g_optim, d_optim, g_ema, device)
  File "finetune_stylegan.py", line 159, in train
    r1_loss = d_r1_loss(real_pred, real_img)
  File "/home/donghyun/Desktop/training/DualStyleGAN/util.py", line 71, in d_r1_loss
    grad_real, = autograd.grad(
  File "/home/donghyun/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/autograd/__init__.py", line 276, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/donghyun/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/home/donghyun/Desktop/training/DualStyleGAN/model/stylegan/non_leaking.py", line 352, in backward
    grad_input, grad_grid = GridSampleBackward.apply(grad_output, input, grid)
  File "/home/donghyun/Desktop/training/DualStyleGAN/model/stylegan/non_leaking.py", line 361, in forward
    grad_input, grad_grid = op(grad_output, input, grid, 0, 0, False)
TypeError: 'tuple' object is not callable
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 17115) of binary: /home/donghyun/anaconda3/envs/dualstylegan_env/bin/python
Traceback (most recent call last):
  File "/home/donghyun/anaconda3/envs/dualstylegan_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/donghyun/anaconda3/envs/dualstylegan_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/donghyun/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/donghyun/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/donghyun/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/donghyun/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/donghyun/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/donghyun/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
finetune_stylegan.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-11-11_01:36:27
  host      : kr-03
  rank      : 0 (local_rank: 0)

**Comment by williamyang1991** [comment]
https://github.com/williamyang1991/DualStyleGAN/tree/main/model/stylegan/op_cpu
you can change to CPU compatible version to avoid using conv2d_gradfix.py

**Comment by williamyang1991** [comment]
conv2d_gradfix.py is from stylegan2-pytorch, or you can check similar issues in 
https://github.com/rosinality/stylegan2-pytorch/issues
to see if there are any solution

**Comment by dongyun-kim-arch** [comment]
I see. I thought this is because of the multi GPU setting.

I wonder about your training process when creating different models such as cartoon or Pixar. 
Did you train all the models from Facial Destylization to optimization? or skip step 2 in Facial Destylization or any other steps?

**Comment by williamyang1991** [comment]
all process
only skip Progressive Fine-Tuning step 1 & 2 by loading the pretrained model
