### ISSUE TITLE
Unable to train with custom dataset

### ISSUE THREAD

**Issue by PS-AI** [williamyang1991/DualStyleGAN#49]
Hi,
Thanks for putting out this work.
I am unable to train with my custom images dataset. The training is failing in the second step of Facial destylization : "Step 2: Fine-tune StyleGAN".

This is the same as an issue reported earlier by @dongyun-kim-arch.

I have given the error message below.

load model: ./checkpoint/stylegan2-ffhq-config-f.pt
  0%|                                                                                                                 | 0/1 [00:00<?, ?it/s]/home/azureuser/DualStyleGAN_dataPrep/DualStyleGAN/model/stylegan/op/conv2d_gradfix.py:88: UserWarning: conv2d_gradfix not supported on PyTorch 1.12.1+cu102. Falling back to torch.nn.functional.conv2d().
  warnings.warn(
  0%|                                                                                                                 | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "finetune_stylegan.py", line 391, in <module>
    train(args, loader, generator, discriminator, g_optim, d_optim, g_ema, device)
  File "finetune_stylegan.py", line 159, in train
    r1_loss = d_r1_loss(real_pred, real_img)
  File "/home/azureuser/DualStyleGAN_dataPrep/DualStyleGAN/util.py", line 71, in d_r1_loss
    grad_real, = autograd.grad(
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 276, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/home/azureuser/DualStyleGAN_dataPrep/DualStyleGAN/model/stylegan/non_leaking.py", line 352, in backward
    grad_input, grad_grid = GridSampleBackward.apply(grad_output, input, grid)
  File "/home/azureuser/DualStyleGAN_dataPrep/DualStyleGAN/model/stylegan/non_leaking.py", line 361, in forward
    grad_input, grad_grid = op(grad_output, input, grid, 0, 0, False)
TypeError: 'tuple' object is not callable
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 99134) of binary: /home/azureuser/anaconda3/envs/dualstylegan_env/bin/python3
Traceback (most recent call last):
  File "/home/azureuser/anaconda3/envs/dualstylegan_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/azureuser/anaconda3/envs/dualstylegan_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/azureuser/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
finetune_stylegan.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-11-11_12:08:03
  host      : asr-training.internal.cloudapp.net
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 99134)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by williamyang1991** [comment]
I have no idea of this error.
For errors found in the code from DualStyleGAN/model/stylegan, I think you can try to directly pose issues in https://github.com/rosinality/stylegan2-pytorch for help.

**Comment by exceedzhang** [comment]
> I have no idea of this error.
> For errors found in the code from DualStyleGAN/model/stylegan, I think you can try to directly pose issues in https://github.com/rosinality/stylegan2-pytorch for help.

Can you give me some guidance when I encounter similar problems? thank you！@williamyang1991 

python finetune_stylegan.py --iter 600 --batch 4 --size 1024 --ckpt ./checkpoint/stylegan2-ffhq-config-f.pt --style fantasy --augment ./data/fantasy/lmdb/

Load options
ada_every: 256
ada_length: 500000
ada_target: 0.6
augment: True
augment_p: 0
batch: 4
channel_multiplier: 2
ckpt: ./checkpoint/stylegan2-ffhq-config-f.pt
d_reg_every: 16
g_reg_every: 4
iter: 600
local_rank: 0
lr: 0.002
mixing: 0.9
model_path: ./checkpoint/
n_sample: 9
path: ./data/fantasy/lmdb/
path_batch_shrink: 2
path_regularize: 2
r1: 10
save_every: 10000
size: 1024
style: fantasy
wandb: False
**************************************************************************************************
load model: ./checkpoint/stylegan2-ffhq-config-f.pt
  0%|                                                                                                               | 0/600 [00:00<?, ?it/s]/root/DualStyleGAN/model/stylegan/op/conv2d_gradfix.py:88: UserWarning: conv2d_gradfix not supported on PyTorch 1.12.1. Falling back to torch.nn.functional.conv2d().
  warnings.warn(
  0%|                                                                                                               | 0/600 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "finetune_stylegan.py", line 391, in <module>
    train(args, loader, generator, discriminator, g_optim, d_optim, g_ema, device)
  File "finetune_stylegan.py", line 159, in train
    r1_loss = d_r1_loss(real_pred, real_img)
  File "/root/DualStyleGAN/util.py", line 71, in d_r1_loss
    grad_real, = autograd.grad(
  File "/opt/miniconda3/envs/vtoonify/lib/python3.8/site-packages/torch/autograd/__init__.py", line 276, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/opt/miniconda3/envs/vtoonify/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/root/DualStyleGAN/model/stylegan/non_leaking.py", line 352, in backward
    grad_input, grad_grid = GridSampleBackward.apply(grad_output, input, grid)
  File "/root/DualStyleGAN/model/stylegan/non_leaking.py", line 361, in forward
    grad_input, grad_grid = op(grad_output, input, grid, 0, 0, False)
TypeError: 'tuple' object is not callable

**Comment by Normale** [comment]
Might be wrong, but I had similar issue and solved it replacing this code:
```py
        # DualStyleGAN\model\stylegan\non_leaking.py 
        # Line 360
        op = torch._C._jit_get_operation("aten::grid_sampler_2d_backward")
        grad_input, grad_grid = op(grad_output, input, grid, 0, 0, False)
```
with this one:
```
        output_mask = (ctx.needs_input_grad[1], ctx.needs_input_grad[2])
        op, _ = torch._C._jit_get_operation("aten::grid_sampler_2d_backward")
        grad_input, grad_grid = op(grad_output, input, grid, 0, 0, False, output_mask)
```
