### ISSUE TITLE
Problem with training

### ISSUE THREAD

**Issue by dongyun-kim-arch** [williamyang1991/DualStyleGAN#50]
Hello,

I faced this problem when fine-tuning stylegen model. I am not sure what cause this error, either dualstylegan or stylegen, but it would be great if someone could have a look at it.

Traceback (most recent call last):
  File "finetune_stylegan.py", line 14, in <module>
    from util import data_sampler, requires_grad, accumulate, sample_data, d_logistic_loss, d_r1_loss, g_nonsaturating_loss, g_path_regularize, make_noise, mixing_noise, set_grad_none
  File "/home/donghyun/Desktop/training/DualStyleGAN/util.py", line 10, in <module>
    from model.stylegan.op import conv2d_gradfix
  File "/home/donghyun/Desktop/training/DualStyleGAN/model/stylegan/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/donghyun/Desktop/training/DualStyleGAN/model/stylegan/op/fused_act.py", line 11, in <module>
    fused = load(
  File "/home/donghyun/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 969, in load
    return _jit_compile(
  File "/home/donghyun/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1196, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/donghyun/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1547, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/home/donghyun/anaconda3/envs/dualstylegan_env/lib/python3.8/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/donghyun/anaconda3/envs/dualstylegan_env/lib/python3.8/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/donghyun/.cache/torch_extensions/fused/fused.so: undefined symbol: _ZN3c104cuda20getCurrentCUDAStreamEa
Traceback (most recent call last):
  File "/home/donghyun/anaconda3/envs/dualstylegan_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/donghyun/anaconda3/envs/dualstylegan_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/donghyun/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/donghyun/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/donghyun/anaconda3/envs/dualstylegan_env/bin/python', '-u', 'finetune_stylegan.py', '--local_rank=0', '--iter', '600', '--batch', '4', '--ckpt', './checkpoint/stylegan2-ffhq-config-f.pt', '--style', 'mystyle', '--augment', './data/mystyle/lmdb/']' returned non-zero exit status 1.

**Comment by williamyang1991** [comment]
This is clearly the problem with your environment and stylegan/op/

have you ever tried the solution of https://github.com/williamyang1991/DualStyleGAN/issues/48#issuecomment-1311522463 and https://github.com/williamyang1991/DualStyleGAN/issues/48#issuecomment-1311524028

**Comment by dongyun-kim-arch** [comment]
You are right. The problem is related to my environment. I changed model.stylegan.op to model.stylegan.op_cpu in stylegan/model.py, util.py and **'non_leaking.py'**.
it seems the training starts, but takes more time than I expected. 

Is there no way to utilize my GPU resource? I spent lots of time managing CUDA and GPU environment settings, but sad that I am not able to use it ...

**Comment by dongyun-kim-arch** [comment]
I managed to train step 2 in Facial Destylization, but faced another problem in step 3 in Facial Destylization.
I tried it twice, but the error occurred again... it seems there is a problem when loading images, but it's so weird to see the error in the middle of the training...

Load options
batch: 8
data_path: ./data/
iter: 300
model_name: finetune-000600.pt
model_path: ./checkpoint/
style: glamour
truncation: 0.7
**************************************************
Loading pSp from checkpoint: ./checkpoint/encoder.pt
Setting up Perceptual loss...
Loading model from: /home/donghyun/Desktop/TWO/AI_filter/training/DualStyleGAN/model/stylegan/lpips/weights/v0.1/vgg.pth
...[net-lin [vgg]] initialized
...Done
Loading ResNet ArcFace
Load models successfully!
[000/301] Lperc: 1.772; Lnoise: 0.000; LID: 0.170; Lreg: 0.376; lr: 0.000: 100%|████████████████████████████████████████| 300/300 [09:23<00:00,  1.88s/it]
[008/301] Lperc: 1.722; Lnoise: 0.000; LID: 0.191; Lreg: 0.340; lr: 0.000: 100%|████████████████████████████████████████| 300/300 [09:23<00:00,  1.88s/it]
[016/301] Lperc: 1.838; Lnoise: 0.000; LID: 0.208; Lreg: 0.372; lr: 0.000: 100%|████████████████████████████████████████| 300/300 [09:23<00:00,  1.88s/it]
[024/301] Lperc: 1.695; Lnoise: 0.000; LID: 0.202; Lreg: 0.355; lr: 0.000: 100%|████████████████████████████████████████| 300/300 [09:23<00:00,  1.88s/it]
[032/301] Lperc: 1.871; Lnoise: 0.000; LID: 0.214; Lreg: 0.352; lr: 0.000: 100%|████████████████████████████████████████| 300/300 [09:23<00:00,  1.88s/it]
[040/301] Lperc: 1.594; Lnoise: 0.000; LID: 0.209; Lreg: 0.331; lr: 0.000: 100%|████████████████████████████████████████| 300/300 [09:23<00:00,  1.88s/it]
[048/301] Lperc: 1.796; Lnoise: 0.000; LID: 0.208; Lreg: 0.343; lr: 0.000: 100%|████████████████████████████████████████| 300/300 [09:23<00:00,  1.88s/it]
[056/301] Lperc: 1.555; Lnoise: 0.000; LID: 0.203; Lreg: 0.337; lr: 0.000: 100%|████████████████████████████████████████| 300/300 [09:23<00:00,  1.88s/it]
[064/301] Lperc: 1.702; Lnoise: 0.000; LID: 0.192; Lreg: 0.355; lr: 0.000: 100%|████████████████████████████████████████| 300/300 [09:23<00:00,  1.88s/it]
[072/301] Lperc: 1.629; Lnoise: 0.000; LID: 0.205; Lreg: 0.362; lr: 0.000: 100%|████████████████████████████████████████| 300/300 [09:23<00:00,  1.88s/it]
[080/301] Lperc: 1.528; Lnoise: 0.000; LID: 0.186; Lreg: 0.334; lr: 0.000: 100%|████████████████████████████████████████| 300/300 [09:23<00:00,  1.88s/it]
[088/301] Lperc: 1.658; Lnoise: 0.000; LID: 0.177; Lreg: 0.345; lr: 0.000: 100%|████████████████████████████████████████| 300/300 [09:23<00:00,  1.88s/it]
[096/301] Lperc: 1.451; Lnoise: 0.000; LID: 0.181; Lreg: 0.359; lr: 0.000: 100%|████████████████████████████████████████| 300/300 [09:23<00:00,  1.88s/it]
[104/301] Lperc: 1.474; Lnoise: 0.000; LID: 0.207; Lreg: 0.338; lr: 0.000: 100%|████████████████████████████████████████| 300/300 [09:23<00:00,  1.88s/it]
[112/301] Lperc: 1.604; Lnoise: 0.000; LID: 0.229; Lreg: 0.381; lr: 0.000: 100%|████████████████████████████████████████| 300/300 [09:23<00:00,  1.88s/it]
[120/301] Lperc: 1.340; Lnoise: 0.000; LID: 0.175; Lreg: 0.355; lr: 0.000: 100%|████████████████████████████████████████| 300/300 [09:23<00:00,  1.88s/it]
[128/301] Lperc: 1.437; Lnoise: 0.000; LID: 0.168; Lreg: 0.342; lr: 0.000: 100%|████████████████████████████████████████| 300/300 [09:23<00:00,  1.88s/it]
[136/301] Lperc: 1.697; Lnoise: 0.000; LID: 0.229; Lreg: 0.362; lr: 0.000: 100%|████████████████████████████████████████| 300/300 [09:23<00:00,  1.88s/it]
Traceback (most recent call last):
  File "destylize.py", line 133, in <module>
    img = transform(Image.open(os.path.join(datapath, file)).convert("RGB"))
  File "/home/donghyun/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/PIL/Image.py", line 2968, in open
    fp = builtins.open(filename, "rb")
IsADirectoryError: [Errno 21] Is a directory: './data/glamour/images/train/images'
Segmentation fault (core dumped)
