### ISSUE TITLE
AttributeError: module 'model.stylegan' has no attribute 'lpips'

### ISSUE THREAD

**Issue by YiingWei** [williamyang1991/DualStyleGAN#81]
当我在进行Destylize artistic portraits的操作时，输入python3 destylize.py --model_name finetune-000600.pt --batch 1 --iter 300 cartoon，出现下面的报错，请问应该怎么解决呢？
Traceback (most recent call last):
  File "destylize.py", line 17, in <module>
    from model.stylegan import lpips
  File "/root/DualStyleGAN-main/model/stylegan/lpips/__init__.py", line 12, in <module>
    from model.stylegan.lpips import dist_model
  File "/root/DualStyleGAN-main/model/stylegan/lpips/dist_model.py", line 21, in <module>
    from model.stylegan.lpips import networks_basic as networks
  File "/root/DualStyleGAN-main/model/stylegan/lpips/networks_basic.py", line 15, in <module>
    import model.stylegan.lpips as util
AttributeError: module 'model.stylegan' has no attribute 'lpips'

**Comment by williamyang1991** [comment]
It seems `from model.stylegan import lpips` has no problem and `import model.stylegan.lpips` has problem. 

May be you can try to change 
`import model.stylegan.lpips as util` in networks_basic.py
to 
`from model.stylegan import lpips as util`
